
[1001](agents)
endpoint/callerid=1_Melanie_Smith <1001>
inbound_auth/username=1001
inbound_auth/password=
endpoint/context=from-oml

[1003](agents)
endpoint/callerid=2_felo_macias <1003>
inbound_auth/username=1003
inbound_auth/password=
endpoint/context=from-oml

[1001](agents)
endpoint/callerid=1_ <1001>
inbound_auth/username=1001
inbound_auth/password=
endpoint/context=from-oml
