stages:
  - build
  - deploy

build-image:
  stage: build
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
  image: gitlab/dind
  script:
    - cd build/docker && bash build_image.sh
  only:
    - web
    - merge_requests
    - /.*pre-release.*$/
    #- /.*release.*$/
    #- /.*master.*$/

build-rpm:
  stage: build
  variables:
  image: freetechsolutions/fpm-ansible:centos7
  script:
    - cd build/rpm && bash build_rpm.sh
  only:
    - web
    - merge_requests
    - /.*pre-release.*$/
    #- /.*release.*$/
    #- /.*master.*$/

deploy-acd-digitalocean:
  stage: deploy
  environment: DOCTL_DIGITALOCEAN_AIO
  script:
    - bash ~/git_cleanup.sh
    - bash ~/.env_do
    - sleep 30
    - doctl compute droplet create --image $DIGITAL_OCEAN_AIO_IMG --size $DIGITAL_OCEAN_AIO_SIZE --region $DIGITAL_OCEAN_REGION --ssh-keys $TF_VAR_ssh_key_fingerprint --user-data-file ~/omlacd/deploy/first_boot_installer.sh omlgitlab-cicd-acd.$CI_JOB_ID
    - sleep 60
    - IP=$(doctl compute droplet list |grep omlgitlab-cicd-acd.$CI_JOB_ID |awk '{print $3}') && echo "$IP 2 run tests"
    - until curl -sk --head  --request GET https://$IP |grep "302" > /dev/null; do echo "Environment still being installed, sleeping 80 seconds"; sleep 80; done; echo "Environment is up"
    - doctl compute droplet delete -f omlgitlab-cicd-aio.$CI_JOB_ID
  tags:
    - deploy-acd
  only:
    - /.*deploy.*$/
    - /.*pre-release.*$/
    - web
    - merge_requests