stages:
  - build
  - deploy

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
      variables:
        IMG_TAG: latest
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'develop'
      variables:
        IMG_TAG: develop
    - when: always

container-image:
  services:
    - docker:20.10.15-dind-alpine3.15
  image: docker:20.10.15-alpine3.15
  stage: build
  before_script:
    - apk add --no-cache docker-cli-buildx
  script:
    - >-
      docker buildx build
      --file=build/Dockerfile
      --tag=dev
      --target=dev
      .
    - >-
      docker buildx build
      --file=build/Dockerfile
      --tag=run
      --target=run
      .
    - |-
      if [ -n "${DOCKER_USER}" ] && [ -n "${DOCKER_PASSWORD}" ]; then
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
        docker tag run freetechsolutions/omlacd:latest
        docker tag run freetechsolutions/omlacd:$CI_COMMIT_SHA
        docker push docker.io/freetechsolutions/omlacd:latest
        docker push docker.io/freetechsolutions/omlacd:$CI_COMMIT_SHA
      fi
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "oml-dev-2.0"
    - if: $CI_PIPELINE_SOURCE == "web"
