
[TroncalSIP0]
type=wizard
transport=trunk-transport
accepts_registrations=no
accepts_auth=no
sends_registrations=yes
sends_auth=yes
aor/qualify_frequency=60
endpoint/rtp_symmetric=no
endpoint/force_rport=no
endpoint/rewrite_contact=yes
endpoint/timers=yes
endpoint/allow=alaw,ulaw
endpoint/dtmf_mode=rfc4733
endpoint/context=from-pstn
endpoint/from_user=devenv
outbound_auth/username=devenv
outbound_auth/password=devenv
remote_hosts=pstngw:6060
