;
; This file is used by the res_aeap module to configure parameters
; used for AEAP applications.
;
[google]
type=client
url=ws://aeap:9099
codecs=alaw
;
; protocol is the implementation specific sub-protocol
;protocol=speech_to_text
;
; "@" parameters can be specified and are used to to set custom values to
; be passed as "params" in the initial "setup" request.
;@language=es-AR
