; ### PJSIP Agent Transports
[agent-transport]
type=transport
async_operations=1
bind=0.0.0.0:5160
protocol=udp
allow_reload=yes
symmetric_transport=yes

; ### PJSIP Trunk Transports
[trunk-transport]
type=transport
async_operations=1
bind=0.0.0.0:5060
protocol=udp
allow_reload=yes
symmetric_transport=yes
;external_media_address=extern_ip_nat
;external_signaling_address=extern_ip_nat


; ### PJSIP Dialer Trunk Transport
[dialer-transport]
type=transport
async_operations=1
bind=0.0.0.0:5260
protocol=udp
allow_reload=yes
symmetric_transport=yes
