[agent-transport]
type=transport
async_operations=1
bind=0.0.0.0:5160
protocol=udp
allow_reload=yes
symmetric_transport=yes
;external_media_address=extern_ip_nat

[trunk-transport]
type=transport
async_operations=1
bind=0.0.0.0:5060
protocol=udp
allow_reload=yes
symmetric_transport=yes
;external_media_address=extern_ip_nat
;external_signaling_address=extern_ip_nat
;external_signaling_port=extern_port_nat
